# Generated by Django 3.0 on 2020-06-28 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('web', models.URLField(blank=True)),
                ('Numero_Examenes', models.IntegerField(default=0)),
                ('Telefono', models.IntegerField(default=954347604, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('DNI', models.IntegerField(default=77777777, validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
