# Generated by Django 3.0.6 on 2020-07-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Fecha_Examen', models.DateField()),
                ('Fecha_Resultados', models.DateField(blank=True, default=None, null=True)),
                ('Duracion', models.IntegerField(blank=True, default=0)),
                ('Estado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
