# Generated by Django 3.0.6 on 2020-07-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enunciado', models.TextField()),
                ('Resolucion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Esta_en_Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Examen')),
                ('id_Pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Pregunta')),
            ],
        ),
    ]
