# Generated by Django 2.1.15 on 2020-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_esta_en_examen_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='Fecha_Examen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='Fecha_Resultados',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
