# Generated by Django 2.1.15 on 2020-07-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_auto_20200718_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='Nombre',
        ),
    ]
