# Generated by Django 2.1.15 on 2020-07-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_remove_examen_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='Duracion',
            field=models.TimeField(blank=True, default=0),
        ),
    ]
