# Generated by Django 2.1.15 on 2020-07-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_auto_20200718_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100)),
                ('Vacantes', models.IntegerField()),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante_Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escuela_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Escuela')),
                ('Postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Postulante')),
            ],
        ),
    ]
