# Generated by Django 2.1.15 on 2020-07-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0007_area_escuela_postulante_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.IntegerField(default=0)),
                ('Escuela_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Escuela')),
                ('Examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Examen')),
                ('Postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Postulante')),
            ],
        ),
        migrations.RemoveField(
            model_name='postulante_escuela',
            name='Escuela_id',
        ),
        migrations.RemoveField(
            model_name='postulante_escuela',
            name='Postulante_id',
        ),
        migrations.DeleteModel(
            name='Postulante_Escuela',
        ),
    ]
