# Generated by Django 3.0.6 on 2020-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0008_auto_20200719_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='E_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='O1_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='O2_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='O3_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='O4_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='O5_imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Opcion1',
            field=models.TextField(default='No encontrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Opcion2',
            field=models.TextField(default='No encontrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Opcion3',
            field=models.TextField(default='No encontrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Opcion4',
            field=models.TextField(default='No encontrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Opcion5',
            field=models.TextField(default='No encontrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Tema',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sovle',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Resolucion',
            field=models.TextField(blank=True),
        ),
    ]
