# Generated by Django 2.1.15 on 2020-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0009_auto_20200727_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_postulante',
            name='DioExamen',
            field=models.BooleanField(default=False),
        ),
    ]
