# Generated by Django 2.1.15 on 2020-08-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_examen_postulante_dioexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_postulante',
            name='Esta_inscrito',
            field=models.BooleanField(default=False),
        ),
    ]
