# Generated by Django 3.0.6 on 2020-08-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0012_examen_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.TextField(blank=True, default='011111111111111111111111111111111111111111111111111111111111111111111111111111111')),
            ],
        ),
        migrations.AddField(
            model_name='esta_en_examen',
            name='numero_pregunta',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='examen',
            name='Nmro_Preguntas',
            field=models.IntegerField(blank=True, default=80),
        ),
        migrations.AddField(
            model_name='examen',
            name='soluciones',
            field=models.TextField(blank=True, default='011111111111111111111111111111111111111111111111111111111111111111111111111111111'),
        ),
    ]
