# Generated by Django 3.0.6 on 2020-08-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0013_auto_20200809_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_postulante',
            name='Solucionario_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.Solucionario'),
        ),
    ]
