# Generated by Django 3.0.6 on 2020-08-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0019_auto_20200809_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='Nmro_Preguntas',
            field=models.IntegerField(blank=True, default=80),
        ),
    ]
