# Generated by Django 3.0.6 on 2020-08-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0020_auto_20200809_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='soluciones',
            field=models.TextField(blank=True, default='000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
        ),
        migrations.AlterField(
            model_name='solucionario',
            name='respuestas',
            field=models.TextField(blank=True, default='000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
        ),
    ]
