# Generated by Django 2.1.15 on 2020-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0022_auto_20200817_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='Nmro_Preguntas',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='examen',
            name='soluciones',
            field=models.TextField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
        ),
    ]
